/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gato.game;

/**
 *
 * @author Gloriana
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Celda1 = new javax.swing.JButton();
        Celda2 = new javax.swing.JButton();
        Celda3 = new javax.swing.JButton();
        Celda4 = new javax.swing.JButton();
        Celda5 = new javax.swing.JButton();
        Celda6 = new javax.swing.JButton();
        Celda7 = new javax.swing.JButton();
        Celda8 = new javax.swing.JButton();
        Celda9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        Celda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Celda1ActionPerformed(evt);
            }
        });
        jPanel1.add(Celda1);
        jPanel1.add(Celda2);
        jPanel1.add(Celda3);

        Celda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Celda4ActionPerformed(evt);
            }
        });
        jPanel1.add(Celda4);
        jPanel1.add(Celda5);
        jPanel1.add(Celda6);

        Celda7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Celda7ActionPerformed(evt);
            }
        });
        jPanel1.add(Celda7);
        jPanel1.add(Celda8);
        jPanel1.add(Celda9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Celda7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Celda7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Celda7ActionPerformed

    private void Celda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Celda4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Celda4ActionPerformed

    private void Celda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Celda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Celda1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Celda1;
    public javax.swing.JButton Celda2;
    public javax.swing.JButton Celda3;
    public javax.swing.JButton Celda4;
    public javax.swing.JButton Celda5;
    public javax.swing.JButton Celda6;
    public javax.swing.JButton Celda7;
    public javax.swing.JButton Celda8;
    public javax.swing.JButton Celda9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
